package com.takecare.travel.apigateway;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HomeController {
  @GetMapping(value = "/", produces = "text/html")
  public String home() {
    return "<!doctype html>"
        + "<html lang=\"en\"><head>"
        + "<meta charset=\"UTF-8\" />"
        + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
        + "<title>Travel Booking</title>"
        + "<style>"
        + "*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(135deg,#eef6ff,#f8fbff 45%,#ecfff8);color:#172033}"
        + "header{position:relative;overflow:hidden;background:linear-gradient(135deg,#0d47d9,#00b894);color:white;padding:70px 20px 95px;text-align:center}"
        + "header:before{content:'';position:absolute;inset:-80px;background:radial-gradient(circle at 20% 20%,rgba(255,255,255,.28),transparent 32%),radial-gradient(circle at 85% 30%,rgba(255,255,255,.18),transparent 28%)}"
        + "header>*{position:relative}header h1{margin:0 0 14px;font-size:clamp(38px,7vw,68px);letter-spacing:-2px}header p{margin:0 auto;font-size:20px;line-height:1.6;opacity:.95;max-width:820px}"
        + "main{max-width:1180px;margin:-55px auto 45px;padding:0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:20px}.top{display:grid;grid-template-columns:1.4fr .6fr;gap:20px;margin-bottom:20px}@media(max-width:820px){.top{grid-template-columns:1fr}}"
        + ".card{background:rgba(255,255,255,.94);border:1px solid rgba(21,84,160,.10);border-radius:24px;padding:26px;box-shadow:0 18px 50px rgba(18,38,63,.12);backdrop-filter:blur(8px)}.card h2{margin:0 0 14px;color:#105adf}.card p{line-height:1.6}.service{transition:.2s}.service:hover{transform:translateY(-4px);box-shadow:0 22px 58px rgba(18,38,63,.16)}"
        + ".actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}button{border:0;border-radius:14px;padding:13px 17px;background:#155eef;color:white;cursor:pointer;font-weight:800;box-shadow:0 10px 22px rgba(21,94,239,.23)}button:hover{background:#0d4ec7}.secondary{background:#00a97f;box-shadow:0 10px 22px rgba(0,169,127,.20)}.secondary:hover{background:#008f6d}.ghost{background:#edf4ff;color:#155eef;box-shadow:none}.ghost:hover{background:#dceaff}"
        + "label{display:block;font-weight:800;margin-top:12px;color:#25324b}input{width:100%;padding:13px 14px;border:1px solid #d0d7e2;border-radius:14px;margin-top:7px;font-size:15px;background:#fbfdff}input:focus{outline:3px solid rgba(21,94,239,.12);border-color:#155eef}"
        + ".result{margin-top:22px}.output{white-space:pre-wrap;word-break:break-word;background:#0b1220;color:#d8ecff;padding:20px;border-radius:18px;min-height:185px;border:1px solid rgba(255,255,255,.08)}.muted{color:#667085}.pill{display:inline-flex;align-items:center;background:#e8f1ff;color:#1769ff;border-radius:999px;padding:8px 12px;margin:4px;font-weight:800;font-size:13px}.status{display:flex;gap:10px;flex-wrap:wrap}.ok{background:#e9fbf5;color:#008f6d}.warn{background:#fff7e6;color:#b25e00}.error{background:#ffeded;color:#c92a2a}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}"
        + "</style></head><body>"
        + "<header><h1>Travel Booking</h1><p>A clean Spring Cloud microservice travel app with one public Gateway website for flights, hotels and car rentals.</p></header>"
        + "<main><section class=\"top\"><div class=\"card\"><h2>One gateway. Three travel services.</h2><p class=\"muted\">Use the cards below to call each service through the API Gateway. If Render is waking a free service or returns 429, the UI waits and retries automatically.</p><div class=\"status\"><span class=\"pill ok\">Gateway Ready</span><span class=\"pill\">Flight API</span><span class=\"pill\">Hotel API</span><span class=\"pill\">Car API</span></div></div>"
        + "<div class=\"card\"><h2>Live URL</h2><p class=\"muted\">https://travel-booking-gateway.onrender.com</p><div class=\"actions\"><button class=\"ghost\" onclick=\"loadHealth()\">Check health</button></div></div></section>"
        + "<section class=\"grid\"><div class=\"card service\"><div class=\"row\"><h2>✈️ Flights</h2><span class=\"pill\">NYC → LAX</span></div><label>Origin</label><input id=\"origin\" value=\"NYC\"><label>Destination</label><input id=\"destination\" value=\"LAX\"><div class=\"actions\"><button onclick=\"searchFlights()\">Search flights</button><button class=\"secondary\" onclick=\"loadData('/api/flights','Flights')\">Show all</button></div></div>"
        + "<div class=\"card service\"><div class=\"row\"><h2>🏨 Hotels</h2><span class=\"pill\">Los Angeles</span></div><label>Location</label><input id=\"hotelLocation\" value=\"LosAngeles\"><div class=\"actions\"><button onclick=\"searchHotels()\">Search hotels</button><button class=\"secondary\" onclick=\"loadData('/api/hotels','Hotels')\">Show all</button></div></div>"
        + "<div class=\"card service\"><div class=\"row\"><h2>🚗 Cars</h2><span class=\"pill\">Rental</span></div><label>Location</label><input id=\"carLocation\" value=\"LosAngeles\"><div class=\"actions\"><button onclick=\"searchCars()\">Search cars</button><button class=\"secondary\" onclick=\"loadData('/api/cars','Cars')\">Show all</button></div></div></section>"
        + "<section class=\"card result\"><div class=\"row\"><h2>Result</h2><span id=\"state\" class=\"pill warn\">Waiting</span></div><div id=\"result\" class=\"output\">Choose a search above. Requests go to the API Gateway first, then to the correct microservice.</div></section></main>"
        + "<script>const sleep=ms=>new Promise(r=>setTimeout(r,ms));function setState(t,c){const s=document.getElementById('state');s.textContent=t;s.className='pill '+c;}async function requestJson(path){let last;for(let i=0;i<3;i++){const res=await fetch(path,{headers:{Accept:'application/json'}});if(res.ok)return await res.json();last=res.status+' '+res.statusText;if(res.status===429||res.status===502||res.status===503||res.status===504){await sleep((i+1)*1600);continue;}throw new Error(last);}throw new Error(last);}async function loadData(path,title){const box=document.getElementById('result');setState('Loading','warn');box.textContent='Loading '+title+' from '+path+' ...';try{const data=await requestJson(path);setState('Success','ok');box.textContent=JSON.stringify(data,null,2);}catch(e){setState('Service issue','error');box.textContent='The service did not respond successfully. If this is Render free hosting, wait a minute and try again. Gateway environment URLs are already configured in render.yaml.\\n\\n'+e;}}function searchFlights(){loadData('/api/flights/search?origin='+encodeURIComponent(origin.value)+'&destination='+encodeURIComponent(destination.value),'Flights');}function searchHotels(){loadData('/api/hotels/search?location='+encodeURIComponent(hotelLocation.value),'Hotels');}function searchCars(){loadData('/api/cars/search?location='+encodeURIComponent(carLocation.value),'Cars');}function loadHealth(){loadData('/actuator/health','Gateway health');}</script>"
        + "</body></html>";
  }
}